apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zorns-eu-test
  description: test
  annotations:
    github.com/project-slug: zorns-eu/spring-boot-demo
    backstage.io/techdocs-ref: github:https://github.com/zorns-eu/spring-boot-demo
spec:
  type: service
  lifecycle: experimental
  owner: jzorn
